# Generated by Django 3.2.3 on 2021-07-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='user_disliked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='user_liked',
            field=models.BooleanField(default=False),
        ),
    ]
