# Generated by Django 3.2.3 on 2021-08-04 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_following_user_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='follower',
            new_name='user_follower',
        ),
        migrations.AddField(
            model_name='following',
            name='user_following',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='network.user'),
            preserve_default=False,
        ),
    ]
