# Generated by Django 3.2.3 on 2021-08-05 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_rename_user_main_following_usermain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_disliked',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_liked',
        ),
    ]
